Add celery task to clean files in media folder [SP-255]
erick-rivas/django-reference pull request #26
Opened 2023-04-01 05:47 UTC by AngelRodriguez319

2023-04-06 00:23 UTC, erick-rivas requested changes

2023-04-06 00:23 UTC, erick-rivas commented on seed/app/celery.py
> +    try:
Quitar try, catch

2023-04-06 00:23 UTC, erick-rivas commented on models/migrations/0001_initial.py
> +# Generated by Django 3.2.18 on 2023-04-01 03:11
Eliminar migración

2023-04-06 00:23 UTC, erick-rivas commented on seed/app/celery.py
> +)
Aclaración (contestar en comentarios de github)
Esto no afecta nuevos beats de app/celery.py?

2023-04-06 00:23 UTC, erick-rivas commented on seed/app/celery.py
> +        file_names = os.listdir(MEDIA_ROOT)
Excluir folders
Utilizar:  os.path.isfile(file_path)

2023-04-06 00:23 UTC, erick-rivas commented on seed/app/celery.py
> +                timestamp = os.path.getctime(MEDIA_ROOT)
Revisar linea, aquí está obtenido timestamp de la carpeta MEDIA_ROOT, debería ser del archivo, no de la carpeta padre

2023-04-13 06:04 UTC, AngelRodriguez319 commented on seed/app/celery.py
> +)
No, solo cuando se creen en app/celery se debe sobre escribir el app.conf.beat_schedule. Ejemplo

app.config.beat_schedule["execute_example_task"] = {
        'task': app.celery.example_task',
        'schedule': timedelta(minutes=1)
}

2023-09-19 01:39 UTC, merged